//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndoorPlaceInformationAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SensorBoard
    {
        public System.Guid SensorBoardId { get; set; }
        public Nullable<System.Guid> EntranceId { get; set; }
        public System.Guid InSensorId { get; set; }
        public System.Guid OutSensorId { get; set; }
    
        public virtual Entrance Entrance { get; set; }
        public virtual Sensor SensorInside { get; set; }
        public virtual Sensor SensorOutside { get; set; }
    }
}
