// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PlaceStatusOnRaspberry.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Sensor
    {
        /// <summary>
        /// Initializes a new instance of the Sensor class.
        /// </summary>
        public Sensor() { }

        /// <summary>
        /// Initializes a new instance of the Sensor class.
        /// </summary>
        public Sensor(Guid? sensorId = default(Guid?), string name = default(string), int? pinTrigd = default(int?), int? pinEchod = default(int?), bool? insideOne = default(bool?))
        {
            SensorId = sensorId;
            Name = name;
            PinTrigd = pinTrigd;
            PinEchod = pinEchod;
            InsideOne = insideOne;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SensorId")]
        public Guid? SensorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PinTrigd")]
        public int? PinTrigd { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PinEchod")]
        public int? PinEchod { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InsideOne")]
        public bool? InsideOne { get; set; }

    }
}
