// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PlaceStatusOnRaspberry.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SensorBoard
    {
        /// <summary>
        /// Initializes a new instance of the SensorBoard class.
        /// </summary>
        public SensorBoard() { }

        /// <summary>
        /// Initializes a new instance of the SensorBoard class.
        /// </summary>
        public SensorBoard(Guid? sensorBoardId = default(Guid?), Guid? entranceId = default(Guid?), Guid? inSensorId = default(Guid?), Guid? outSensorId = default(Guid?), Entrance entrance = default(Entrance), Sensor sensorInside = default(Sensor), Sensor sensorOutside = default(Sensor))
        {
            SensorBoardId = sensorBoardId;
            EntranceId = entranceId;
            InSensorId = inSensorId;
            OutSensorId = outSensorId;
            Entrance = entrance;
            SensorInside = sensorInside;
            SensorOutside = sensorOutside;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SensorBoardId")]
        public Guid? SensorBoardId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EntranceId")]
        public Guid? EntranceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "InSensorId")]
        public Guid? InSensorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OutSensorId")]
        public Guid? OutSensorId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Entrance")]
        public Entrance Entrance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SensorInside")]
        public Sensor SensorInside { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SensorOutside")]
        public Sensor SensorOutside { get; set; }

    }
}
